mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/maizi/demo/mapper/xml/*.xml
  global-config:
    db-config:
      #配置MyBatis-Plus操作表的默认前缀
      table-prefix: t2_
      #使用数据库的自增策略，注意，该类型请确保数据库设置了id自增否则无效
      id-type: auto
  #配置类型别名所对应的包
  type-aliases-package: com.maizi.demo.pojo

spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatisplus-quick-start?characterEncoding=utf-8&useSSL=false
          username: root
          password: admin123
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatisplus-quick-start_1?characterEncoding=utf-8&useSSL=false
          username: root
          password: admin123
          driver-class-name: com.mysql.cj.jdbc.Driver

